version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 
    commands:
      - echo Installing Node.js dependencies...
      - cd $CODEBUILD_SRC_DIR/frontend
      - npm install
    
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/frontend
      - echo Updating Angular environment for production build...
      
      - mkdir -p src/environments/
      
      - |
        echo "export const environment = {
          production: true,
          apiUrl: 'https://api.${DOMAIN_NAME}/api/v1',
          cognitoUserPoolId: '${COGNITO_USER_POOL_ID}',
          cognitoUserPoolClientId: '${COGNITO_USER_POOL_CLIENT_ID}',
          tmdbApiKey: '${TMDB_API_KEY}'
        };" > src/environments/environment.prod.ts

      - cat src/environments/environment.prod.ts
      
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/frontend
      - echo Building the Angular application...
      - npm run build -- --configuration=production

  post_build:
    commands:
      - echo Deploying Angular application to S3...
      - aws s3 sync dist/movie-mator/browser/ s3://${FRONTEND_S3_BUCKET_NAME} --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist/movie-mator/browser
  discard-paths: yes