version: 0.0

os: linux 

files:
  - source: /
    destination: /tmp/codedeploy-artifacts/

hooks:
  ApplicationStop:
    - location: stop_application.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: stop_application.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: start_application.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: validate_service.sh
      timeout: 300
      runas: root