version: 0.0

os: linux 

files:
  - source: /
    destination: /tmp/codedeploy-artifacts/

hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root