
version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo "Installing Java runtime..."
    runtime-versions:
      java: corretto21
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - REPO_NAME=$(echo $ECR_REPO_URI | cut -d '/' -f 2)
      - IMAGE_TAG=$(echo $(git rev-parse --short HEAD))

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for backend...
      - cd backend
      - mvn clean package -DskipTests
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $REPO_NAME $ECR_REPO_URI:$IMAGE_TAG > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - backend/imageDefinitions.json
  discard-paths: yes