version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo "Installing Java runtime..."
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - export REPO_NAME=$(echo $ECR_REPO_URI | cut -d '/' -f 2)

  build:
    commands:
      - echo "Build started on `date`"
      - cd backend

      # 1. Compile code
      - echo "Compiling application..."
      - mvn clean compile

      # 2. Run Unit Tests
      - echo "Running unit tests..."
      - mvn test

      # 3. Package app
      - echo "Packaging application..."
      - mvn package -DskipTests
      
      # 4. Run Integration Tests
      - echo "Running integration tests (with Testcontainers)..."
      - mvn verify

      # 5. Build Docker image
      - echo "Building the Docker image for backend..."
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest

      - echo "Writing image definitions file..."
      - cd $CODEBUILD_SRC_DIR
      - printf '[{"name":"%s","imageUri":"%s"}]' $REPO_NAME $ECR_REPO_URI:$IMAGE_TAG > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - imageDefinitions.json
    - backend/appspec.yml
    - backend/scripts/**/*
  discard-paths: yes